name: Sync Others

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
jobs:
  repo-sync:
    name: Sync Others
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.5.0
    - name: Create Command
      run: |
         cat > moveProxiesToSync.sh <<- EOF
            moveProxiesToSync() {
              proxies=()
              begin=0
              while read -r line; do
                if [[ \$begin == 1 ]]; then
                  if [[ \$line =~ "^[ ]*-.*$" ]]; then
                    proxies+=("\$line")
                  else
                    break;
                  fi
                fi
                if [[ \$line == "proxies:" ]]; then
                  begin=1
                fi
              done < \$1

              for proxy in "\${proxies[@]}"; do
                echo \$proxy >> \$2
              done
            }
          EOF
          source ./moveProxiesToSync.sh
    - name: Merge files
      id: gitStatus
      run: |
          git remote add aweikeji "https://github.com/ggborr/aweikeji"
          git fetch origin aweikeji --depth=2
          
          git remote add TopFreeProxies "https://github.com/alanbobs999/TopFreeProxies"
          git fetch origin TopFreeProxies --depth=2
          
          aweikejiFile=$( git diff --name-only --diff-filter=AMT awikeji~1 aweikeji | xargs -I{} -- git log -1 --format="%ci {}" {} | sort | tail -1 | cut -d " " -f4)
          git checkout origin/aweikeji $aweikejiFile
          git checkout origin/TopFreeProxies "Eternity.yaml"
          
          echo > "proxies:"
          moveProxiesToSync $aweikejiFile clash_auto
          moveProxiesToSync "Eternity.yaml" clash_auto
          
          git rm $aweikejiFile
          git rm "Eternity.yaml" 
          
          git add clash_auto
          gitStatus="$(git status -s)"
          echo "hadChanged=${#gitStatus}" >> $GITHUB_OUTPUT
          echo $gitStatus
    - name: Commit files
      if: ${{ steps.gitStatus.outputs.hadChanged }}
      run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "Update Clash Auto" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
